Console:
  Disable: false
  Format: text
  IncludeSource: true
  IncludeFullSource: true
  StdOut: false
  Level: "ERROR+1"
File:
  Disable: false
  Format: json
  IncludeSource: true
  IncludeFullSource: true
  Path: "/home/dir"
